### ISSUE TITLE
Pub conflict with  intl 0.18

### ISSUE THREAD

**Issue by Prayer-RecycleSmart** [cloudacy/native_exif#14]
Hey guys,

Can we bump the version so we can align with intl 0.18?

**Comment by p-kuen** [comment]
Sure, can you please submit a PR?

**Comment by Prayer-RecycleSmart** [comment]
@p-kuen Hey Patrick, honestly I tried, but I haven't been able to. I hoped it was something as simple as bumping the version but I get (feels like) other dependency constraints that I can't figure out.
