### ISSUE TITLE
Android UserComment Warning - "Invalid EXIF text encoding for UserComment"

### ISSUE THREAD

**Issue by zehung-yeoh** [cloudacy/native_exif#17]
Hi, I'm trying to write the attribute for 'UserComment' using an Android device. It keeps showing an additional field called 'Warning' as shown below. This issue does not occur when I'm using iPhone. Any idea how to fix this? Thanks

`Warning: Invalid EXIF text encoding for UserComment`

**Comment by d-kuen** [comment]
Hi,

this package uses the JetPack version of the ExifInterface.
A quick search brought me to [this](https://stackoverflow.com/questions/49023824/exifinterface-utf-8-support).

Seems like a platform specific issue, so I will close this issue.
This limitation is now mentioned in the readme.
