### ISSUE TITLE
Exif detail GPS(Latitude,Longitude) not working for iOS in Flutter but it's working fine in Android. 

### ISSUE THREAD

**Issue by vishnuP-Lepton** [cloudacy/native_exif#2]

**Comment by p-kuen** [comment]
Thank you for submitting this issue. Can you please provide further information about what is "not working". Please use the issue description for that. Thanks!

**Comment by vgribok** [comment]
I ran into the same issue on iOS with physical device (not tested on Android) - added attributes not getting saved.

I cloned this repo and found that the "[Update date attribute and add new attribute](https://github.com/cloudacy/native_exif/blob/main/example/lib/main.dart#L88)" does do anything - the 'ImageUniqueID' does not get written.

The "[Create file and write exif data](https://github.com/cloudacy/native_exif/blob/main/example/lib/main.dart#L124)" seems to be working.

**Comment by vgribok** [comment]
I found that user comment metadata gets written, while GPS metadata does not. Looking at another implementation (in Objective-C), it appears GPS metadata can be written with [another, GPS-specific dictionary of the metadata](https://github.com/Beakyn/exif_flutter/blob/master/ios/Classes/ExifPlugin.m#L37). Since this implementation uses only `metadata["{Exif}"]` throughout, I bet writing GPS Exif was never tested.

**Comment by d-kuen** [comment]
`native_exif` didn't support GPS attributes on iOS devices. The referenced commit adds this feature.

We also removed the `ImageUniqueID` example. Thanks for noting this.

Only specific EXIF and GPS attributes can be read or written on each platform. Please have a look at the updated README file for more details.

**Comment by vishnuP-Lepton** [comment]
@vgribok & @d-kuen Thanks for response,
   
            I found that in read me file that iOS also support exif & GPS which should be specific case.
https://user-images.githubusercontent.com/90191642/180699178-29804c1c-6aec-4309-a3c7-bfa2c4c674bd.png

          Let me know what are specific GPS attribute are supported in iOS.

**Comment by d-kuen** [comment]
You should be able to use all keys, listed at https://developer.apple.com/documentation/imageio/gps_dictionary_keys.
Please make sure to use the resolved values and prefix them with `GPS`.
The resolved values may be the same as the part after `kCGImagePropertyGPS` but I didn't check all of them.
