### ISSUE TITLE
Dependabot upgrading unwanted versions

### ISSUE THREAD

**Issue by diegogarciar** [cloudacy/native_exif#28]
Hello, I don't think its a good idea to let the dependabot to make changes on the android folder, the versions should only be increased when recommended by flutter.

in this example, it bumped the Kotlin version and its the only package that is requesting me to increment the Kotlin version on my app.

https://github.com/cloudacy/native_exif/commit/320de9cf9978aaef5837331f8504e135c36b052f

the same can be said for the gradle version being increased just recently

https://github.com/cloudacy/native_exif/commit/d1ed3d08852062e30976d5ecb6adbeaf7b282d7d

**Comment by d-kuen** [comment]
Hello,

thank you for the report.

We reverted the gradle updates and removed the dependabot config.

**Comment by diegog-sf** [comment]
Thank you for your immediate action ;)
