### ISSUE TITLE
getAttribute can't get the value

### ISSUE THREAD

**Issue by LoveBabyForeve** [cloudacy/native_exif#5]
Hi there,
  
await exif.writeAttribute("key", "value");

final key1 = await exif.getAttribute<String>('key');

I can't get the value

**Comment by d-kuen** [comment]
Hi,

it is only possible to read and write values for specific keys, determined by the platform. Please habe a look at the "Platform notes" section of the Readme file.

**Comment by LoveBabyForeve** [comment]
Thank you for your reply
