### ISSUE TITLE
Unable to Read and Write Exif Data.

### ISSUE THREAD

**Issue by shantaramk** [cloudacy/native_exif#6]
### **Input Source:**
![sample](https://user-images.githubusercontent.com/7990309/188317564-9407bd54-e59e-495b-a62d-1e48d11253d9.jpg)

### **Exif Info:**  
<img width="910" alt="Screenshot 2022-09-04 at 7 41 17 PM" src="https://user-images.githubusercontent.com/7990309/188317903-9f1c9ea4-8273-403b-a820-c147c31a1e5c.png">

**Given**: 
 Under **More Info** Section, **Exif** Tab is missing 

### **Output:**  

While reading the EXIF data for the given Image, the Library throws the exception. i.e  No Exif data was found on this image

PlatformException(READ_ERROR, No Exif data was found on this image., null, null)

### **Use Case :**
I want to add custom info in **User Comment key** in exif data.

**Comment by p-kuen** [comment]
Thank you for submitting the issue. By your error message I see you are not using the latest version of native_exif. Could you please try again with the latest version? It's possible that the error was being fixed in the meantime.
