### ISSUE TITLE
How to change x and y pixel resolution and image width and height.

### ISSUE THREAD

**Issue by JarrodLodge** [cloudacy/native_exif#9]
Using a similar library in NodeJS I am able to set the X/Y resolution and the image width and height. I can't seem to make this work with this library.

Code below is from https://github.com/hMatoba/piexifjs
```
zeroth[piexif.ImageIFD.XResolution] = [300, 1];
zeroth[piexif.ImageIFD.YResolution] = [300, 1];
zeroth[piexif.ImageIFD.ImageWidth] = 5;
zeroth[piexif.ImageIFD.ImageHeight] = 7;
```
This is what im trying below, are my tag names wrong?
```
await exif.writeAttributes({
    "ImageWidth": 5,
    "ImageHeight": 7,
    "PixelXDimension": [300, 1],
    "PixelYDimension": [300, 1],
  });
```

**Comment by d-kuen** [comment]
Hi,

only specific attributes are supported by this package. Please have a look [here](https://github.com/cloudacy/native_exif#platform-notes) for more details.

As a workaround we would recommend to resize the image.
